Task 1
Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
•3
•45
•83
•21

Task 1 w


In [45]:

my_file = open("Numbers.txt", "w")

my_file.write(f'{input("please enter first number")}\n')
my_file.write(f'{input("please enter second number")}\n')
my_file.write(f'{input("please enter third number")}\n')
my_file.write(f'{input("please enter fourth number")}\n')

my_file.close()

Task 1 r


In [46]:
#
with open("Numbers.txt","r") as myfile:
    data = myfile.read().replace('\n',',')
    print(data)
myfile.close()

1,2,3,4,


Task 1 a

In [47]:
#Append chosen number to file
my_file = open("Numbers.txt","a")

my_file.write(f'{input("please enter number to append to file")}')

my_file.close()

Task 2

Write a program to ask a student for their percentage mark and convert this to a grade.The conversion will be done in a function called mark_grade

In [8]:
grade_value = {
    80:"A*",
    70:"A",
    60:"B",
    50:"C",
    40:"D",
    0:"F"
}

def mark_grade(percentage_mark):
    for percentage, grade in grade_value .items():
        if percentage_mark >= percentage:
            print(f"Grade Achieved: {grade}") 
            break

try:
    mark_grade(float(input("Please enter your percentage mark")))
except:
    print("Please enter a numeric value")

Grade Achieved: D


Task 2 Extention
•Ask the user for their target grade and print this with their mark
•If their target grade > exam grade display a suitable message
•If their target grade = exam grade display a suitable message
•If their target grade < exam grade display a suitable message

NumPy Tasks
1.Create a 1D array of numbers from 0 to 9 

In [1]:
import numpy as np  

array = np.arange(10)
print (array)   

[0 1 2 3 4 5 6 7 8 9]


2.Create a 3×3 NumPy array of all Boolean value Trues


In [2]:


array = np.ones((3,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.Extract all odd numbers from array of 1-10

In [4]:
array = np.arange(2,11,2)
print( array)

[ 2  4  6  8 10]


4.Replace all odd numbers in an array of 1-10 with the value -1

In [5]:
array = np.arange(1,11)
odd_value = array [array % 2 ==1] = -1
print(array)


[-1  2 -1  4 -1  6 -1  8 -1 10]


5.Convert a 1D array to a 2D array with 2 rows

In [6]:
array =np.arange(1,11)
np.resize(array, 10).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

6.Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals

In [16]:
a = np.arange(1,10,1).reshape(3,3)
b = np.arange(11,20,1).reshape(3,3)
c = np.dot(a,b)
d = np.sum(c)

print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
2079


NumPy Tasks Extension

1.Create the following pattern without hardcoding. Use only NumPy functions.

In [32]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

2.In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) –remove all repeating  items present in array b

In [36]:

a = [1,2,3,4,5]
b = [4,5,6,7,8,9]

new_list = list(sorted(set(b)-set(a))) 
print(new_list)

[6, 7, 8, 9]


3.Get all items between 3 and 7 from a and b and sum them together

In [3]:
a = np.arange(0,6)
b = np.arange(4,10)
c = np.concatenate((a, b))
print(c)
c[np.logical_and(c>3,c<7)].sum()

[0 1 2 3 4 5 4 5 6 7 8 9]


24